// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0rDiWzd4S1w4vz7_yXYFGLhb80gzwPJE',
    appId: '1:739222407970:web:51c13491fca8e5f3c5f37b',
    messagingSenderId: '739222407970',
    projectId: 'pubs-financial',
    authDomain: 'pubs-financial.firebaseapp.com',
    storageBucket: 'pubs-financial.firebasestorage.app',
    measurementId: 'G-H0TZ1GFJQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD22UGYRDw3QULvVT4-bFTYzi7b7G1VHik',
    appId: '1:739222407970:android:4c5773039e3209fec5f37b',
    messagingSenderId: '739222407970',
    projectId: 'pubs-financial',
    storageBucket: 'pubs-financial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBssPkeafGrN8E2AWojfUnHJR16ugnuLGE',
    appId: '1:739222407970:ios:fd4e887c400325eec5f37b',
    messagingSenderId: '739222407970',
    projectId: 'pubs-financial',
    storageBucket: 'pubs-financial.firebasestorage.app',
    iosBundleId: 'com.duxtonpubs.pubsfinancial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBssPkeafGrN8E2AWojfUnHJR16ugnuLGE',
    appId: '1:739222407970:ios:fd4e887c400325eec5f37b',
    messagingSenderId: '739222407970',
    projectId: 'pubs-financial',
    storageBucket: 'pubs-financial.firebasestorage.app',
    iosBundleId: 'com.duxtonpubs.pubsfinancial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0rDiWzd4S1w4vz7_yXYFGLhb80gzwPJE',
    appId: '1:739222407970:web:52784bfdb3487538c5f37b',
    messagingSenderId: '739222407970',
    projectId: 'pubs-financial',
    authDomain: 'pubs-financial.firebaseapp.com',
    storageBucket: 'pubs-financial.firebasestorage.app',
    measurementId: 'G-C7D04H521W',
  );
}
